included:
  - Sources
  - Tests

nesting:
  type_level: 2

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - empty_string
  - first_where
  - let_var_whitespace
  - literal_expression_end_indentation
  - number_separator
  - operator_usage_whitespace
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

identifier_name:
  excluded:
    - id
    - or
